### ISSUE TITLE
How to receive notification from server

### ISSUE THREAD

**Issue by yinhm** [calmh/jsonrpc#2]
I'v been evaluated a couple of rpc packages, none of them seems standard compliant except your jsonrpc package.

I was looking for a bidirectional rpc package, it seems your jsonrpc only have client support. I was thinking about using jsonrpc in conjugation with muxado[1] which have stream multiplexing support. Hopefully can send notification from server to client(maybe I was wrong about this assumption.)

My question was: say I already have a server which can send rpc notification to the client, how can I using jsonrpc to react with it?

Disclose: I was new to golang.

[1] https://github.com/inconshreveable/muxado

**Comment by calmh** [comment]
You can't, unfortunately. That's one of the things that suck with this library. Another is the error handling. Sorry. .)

**Comment by yinhm** [comment]
No worry.

I ended up forking birpc from https://github.com/tv42/birpc, make it standard not-compliant to just meet my specific needs[1].

And gRPC for newer project if I have server and client both in control.

Also, my golang skill got a lot better, :-)

[1] https://github.com/yinhm/birpc
