### ISSUE TITLE
Params in the request is sent as an array

### ISSUE THREAD

**Issue by rathinaganesh** [calmh/jsonrpc#3]
When a JSON-RPC request is made, the contents of the params are sent as a JSON array and not as an individual object. 
For example, here is the request sent to the JSON-RPC server -
{"id":0,"jsonrpc":"2.0","method":"test_method","params": [{"value1":7}] }

Instead it should be -
{"id":0,"jsonrpc":"2.0","method":"test_method","params": {"value1":7} }

Thanks.

**Comment by calmh** [comment]
Yeah, it's written for the array style of parameters, not the object style.

**Comment by rathinaganesh** [comment]
Thanks. Is there anyway, I can change that?
